jobs:
- job: LintCode
  displayName: Lint code
  steps:
    - script: |
        az bicep build --file 01-firstAppTodo/deploy-azure/infra-as-code.bicep
      name: LintBicepCode
      displayName: Run Bicep linter