parameters:
# This parameter should reflect the same name as registered in Azure DevOps
# Currently, my solution has 2 envs type: Dev and Prod
- name: environmentType
  type: string
  default: Dev
- name: environmentName
  type: string
  default: dev1
- name: subnetAddressPrefix
  type: string
  default: 1
- name: deploymentLocation
  type: string
  default: westeurope
- name: deploymentLocationSuffix
  type: string
  default: we
- name: serviceConnectionName
  type: string
  default: 'Azure Personal'

stages:
- stage: Deploy_${{parameters.environmentName}}
  displayName: Deploy to (${{parameters.environmentName}} environment)
  variables:
    resourceGroupName: 'rg-firstapp-${{parameters.environmentName}}-${{parameters.deploymentLocationSuffix}}'
  jobs:
  - deployment: DeployWebsite
    pool:
        vmImage: 'ubuntu-latest'
    displayName: Deploy website
    environment: ${{parameters.environmentType}}
    strategy:
      runOnce:
        deploy:
          
          steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: '${{parameters.serviceConnectionName}}'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az group create --name $(resourceGroupName) --location ${{parameters.deploymentLocation}}'

          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '${{parameters.serviceConnectionName}}'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resourceGroupName)'
              location: '${{parameters.deploymentLocation}}'
              templateLocation: 'Linked artifact'
              csmFile: '01-firstAppTodo/deploy-azure/infra-as-code.bicep'
              overrideParameters: ' -environment ${{parameters.environmentName}} -subnetAddressPrefix ${{parameters.subnetAddressPrefix}} -location ${{parameters.deploymentLocation}} -location_suffix ${{parameters.deploymentLocationSuffix}}'
              deploymentMode: 'Complete'
              deploymentName: 'DeployPipelineTemplate'
          - task: UseDotNet@2
            inputs:
              version: '6.0.x'
              includePreviewVersions: true
          - script: dotnet build --configuration Release
            displayName: 'Build .NET 6 Application'
            workingDirectory: '01-firstAppTodo/'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'publish'
              publishWebProjects: true

          #Publish it to the Azure App Service
          - task: AzureWebApp@1
            # This is here because theres an issue with this task: the resource cannot be found
            retryCountOnTaskFailure: 10
            inputs:
              appType: webApp
              azureSubscription: ${{parameters.serviceConnectionName}} #this is the name of the SPN
              # Ideally this should be retrieve as output, this is to be implemented
              # from docs, it seems we can use deploymentOutputs parameter from AzureResourceManagerTemplateDeployment
              appName: 'webapptodofirstapp${{parameters.environmentName}}${{parameters.deploymentLocationSuffix}}' #App Service's unique name
              package: $(System.DefaultWorkingDirectory)/01-firstAppTodo/**/*.zip

- stage: SmokeTest_${{parameters.environmentName}}
  displayName: Smoke Test (${{parameters.environmentName}} Environment)
  jobs:
  - job: SmokeTest
    displayName: Smoke test
    steps:
      - script: echo Smoke test should be implemented here!