parameters:
- name: environmentName
  type: string
  default: dev1
- name: subnetAddressPrefix
  type: string
  default: 1
- name: deploymentLocation
  type: string
  default: westeurope
- name: deploymentLocationSuffix
  type: string
  default: we
- name: serviceConnectionName
  type: string
  default: 'Azure Personal'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 01-firstAppTodo/infra-as-code.bicep

variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: ${{parameters.serviceConnectionName}}
  resourceGroupName: 'rg-firstapp-${{parameters.environmentName}}-${{parameters.deploymentLocationSuffix}}'
  location: ${{parameters.deploymentLocation}}
  templateFile: './01-firstAppTodo/deploy-azure/infra-as-code.bicep'

jobs:
- job: DeployBicepAzure
  displayName: Deploy Bicep Azure

  pool:
    vmImage: $(vmImageName)

  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az group create --name $(resourceGroupName) --location $(location)'

  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: '$(azureServiceConnection)'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(resourceGroupName)'
      location: '$(location)'
      templateLocation: 'Linked artifact'
      csmFile: '$(templateFile)'
      overrideParameters: ' -environment ${{parameters.environmentName}} -subnetAddressPrefix ${{parameters.subnetAddressPrefix}} -location $(location) -location_suffix ${{parameters.deploymentLocationSuffix}}'
      deploymentMode: 'Complete'
      deploymentName: 'DeployPipelineTemplate'