parameters:
# This parameter should reflect the same name as registered in Azure DevOps
# Currently, my solution has 2 envs type: Dev and Prod
- name: environmentType
  type: string
  default: Dev
- name: environmentName
  type: string
  default: dev1
- name: subnetAddressPrefix
  type: string
  default: 1
- name: deploymentLocation
  type: string
  default: westeurope
- name: deploymentLocationSuffix
  type: string
  default: we
- name: serviceConnectionName
  type: string
  default: 'Azure Personal'

variables:
  vmImageName: 'ubuntu-latest'
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.x'
  azureServiceConnection: ${{parameters.serviceConnectionName}}
  resourceGroupName: 'rg-firstapp-${{parameters.environmentName}}-${{parameters.deploymentLocationSuffix}}'
  location: ${{parameters.deploymentLocation}}
  templateFile: './01-firstAppTodo/deploy-azure/infra-as-code.bicep'
  # Ideally this should be retrieve as output, this is to be implemented
  # from docs, it seems we can use deploymentOutputs parameter from AzureResourceManagerTemplateDeployment
  azureAppServiceName: 'webapptodofirstapp${{parameters.environmentName}}${{parameters.deploymentLocationSuffix}}'

stages:
- stage: Deploy_${{parameters.environmentName}}
  displayName: Deploy to (${{parameters.environmentName}} environment)
  jobs:
  - deployment: DeployWebsite
    pool:
        vmImage: $(vmImageName)
    displayName: Deploy website
    environment: ${{parameters.environmentType}}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az group create --name $(resourceGroupName) --location $(location)'

          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(azureServiceConnection)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resourceGroupName)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(templateFile)'
              overrideParameters: ' -environment ${{parameters.environmentName}} -subnetAddressPrefix ${{parameters.subnetAddressPrefix}} -location $(location) -location_suffix ${{parameters.deploymentLocationSuffix}}'
              deploymentMode: 'Complete'
              deploymentName: 'DeployPipelineTemplate'
          - task: UseDotNet@2
            inputs:
              version: $(dotNetVersion)
              includePreviewVersions: true
          - script: dotnet build --configuration $(buildConfiguration)
            displayName: 'Build .NET 6 Application'
            workingDirectory: '01-firstAppTodo/'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'publish'
              publishWebProjects: true

          #Publish it to the Azure App Service
          - task: AzureWebApp@1
            # This is here because theres an issue with this task: the resource cannot be found
            retryCountOnTaskFailure: 10
            inputs:
              appType: webApp
              azureSubscription: $(azureServiceConnection) #this is the name of the SPN
              appName: $(azureAppServiceName) #App Service's unique name
              package: $(System.DefaultWorkingDirectory)/01-firstAppTodo/**/*.zip

- stage: SmokeTest_${{parameters.environmentName}}
  displayName: Smoke Test (${{parameters.environmentName}} Environment)
  jobs:
  - job: SmokeTest
    displayName: Smoke test
    steps:
      - script: echo Smoke test should be implemented here!