db:
  connstring: AccountEndpoint=https://cosmos-todoakswebapp-dev1-we.documents.azure.com:443/;AccountKey=AvTkXWObpU8qIMd3ElbvIcYbxLTPcFHyHNF8VAsBQqqbXyhwkpYDQkLwCjbQxBeEGxkaczALD6CAEgElLaDsjQ==;
  dbname: Tasks
  containername: Item
acrurl: acrtodoakswebappwe.azurecr.io