#This is a Build Deploy Pipeline for .NET 6 Web App to Azure App Service using Azure DevOps Pipeline

trigger:
  branches:
    include:
      - main
  paths:
    include:
    - 01-firstAppTodo

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.x'
  azureSPNName: 'Azure Personal' #get it from your AzureDevOps portal
  azureAppServiceName: 'webapptodofirstappdev3we' #get it from your Azure portal

# Build the app for .NET 6 framework
steps:
- task: UseDotNet@2
  inputs:
    version: $(dotNetVersion)
    includePreviewVersions: true
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET 6 Application'
  workingDirectory: '01-firstAppTodo/'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

# # Package the file and uploads them as an artifact of the build
# - task: PublishPipelineArtifact@1
#   inputs:
#     targetPath: '$(Build.ArtifactStagingDirectory)' 
#     artifactName: 'todowebApp'

#Publish it to the Azure App Service
- task: AzureWebApp@1
  retryCountOnTaskFailure: 10
  inputs:
    appType: webApp
    azureSubscription: $(azureSPNName) #this is the name of the SPN
    appName: $(azureAppServiceName) #App Service's unique name
    package: $(System.DefaultWorkingDirectory)/01-firstAppTodo/**/*.zip