trigger: none

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'Azure Personal'
  resourceGroupName: 'rg-firstapp-dev3-we'
  location: 'westeurope'
  templateFile: './infra-as-code.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    overrideParameters: ' -environment dev3 -subnetAddressPrefix 3 -location $(location) -location_suffix we'
    deploymentMode: 'Complete'
    deploymentName: 'DeployPipelineTemplate'