version: '3.4'

services:
  todowebapp.api:
    container_name: todowebappapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=cosmosdb-connection-string-here!!!
      - CosmosDb__DatabaseName=Tasks
      - CosmosDb__ContainerName=Item
    ports:
      - "80"

  todowebapp.client:
    container_name: todowebappclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ToDoAPIUrl=http://todowebappapi
    ports:
      - "80"
    depends_on: 
        - todowebapp.api

