name: 02 CI CD Full Workflow with Approvals

on:
  workflow_dispatch:
    inputs:
      dev-env:
        description: 'dev environment - ex.: dev1'
        required: true
        type: string
        default: dev1
      location:
        description: 'location - ex.: westeurope'
        required: true
        type: string
        default: westeurope
      location_suffix:
        description: 'location suffix - ex.: we'
        required: true
        type: string
        default: we
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]



  # Two environments need to be created: development and production

jobs:
  build_and_deploy_dev_env:
    uses: rmoreirao/AzureLearning/.github/workflows/02-github-ci-cd-workflow-generic.yml@main
    secrets: inherit
      # url: ${{ steps.deploy-dev.outputs.webAppUrl }}
    # steps:
    # - name: Build and Deploy Development environment
    #   id: deploy-dev
    # Docs on Reusing WF: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    with:
      environment_type: development
      environment: ${{ inputs.dev-env }}
      location: ${{ inputs.location }}
      location_suffix: ${{ inputs.location_suffix }}

  build_and_deploy_prod_env:
    needs: build_and_deploy_dev_env
    uses: rmoreirao/AzureLearning/.github/workflows/02-github-ci-cd-workflow-generic.yml@main
    secrets: inherit
      # url: ${{ steps.deploy-dev.outputs.webAppUrl }}
    # steps:
    # - name: Build and Deploy Development environment
    #   id: deploy-dev
    # Docs on Reusing WF: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    with:
      environment_type: production
      environment: prod
      location: ${{ inputs.location }}
      location_suffix: ${{ inputs.location_suffix }}