name: 02 CI CD Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  rgName: rg-tododockerwebapp-dev-we
  location: westeurope
  location_suffix: we
  environment: dev

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    
    - name: Log in with Azure
      uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: az group create --name $rgName --location $location --subscription ${{ secrets.SUBSCRIPTION_ID }}

    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: $rgName
        template: 02-AspNetCore_Docker_Github/infra-as-code.bicep
        parameters: 'location=$location location_suffix=$location_suffix environment=$environment'
        failOnStdErr: false
