name: 02 CI CD Full Workflow with Approvals

on:
  workflow_dispatch:
    inputs:
      dev-env:
        description: 'dev environment - ex.: dev1'
        required: true
        type: string
        default: dev1
      location:
        description: 'location - ex.: westeurope'
        required: true
        type: string
        default: westeurope
      location_suffix:
        description: 'location suffix - ex.: we'
        required: true
        type: string
        default: we
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]



jobs:
  
  build_dev_env:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ steps.deploy-dev.outputs.webAppUrl }}
    steps:
    - name: Build and Deploy Development environment
      id: deploy-dev
    # Docs on Reusing WF: https://docs.github.com/en/actions/using-workflows/reusing-workflows
      uses: rmoreirao/AzureLearning/.github/workflows/02-github-ci-cd-workflow-generic.yml@main
      with:
        environment: ${{ inputs.dev-env }}
        location: ${{ inputs.location }}
        location_suffix: ${{ inputs.location_suffix }}

  build_prod_env:
    needs: build_dev_env
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - name: Build and Deploy Production environment
    # Docs on Reusing WF: https://docs.github.com/en/actions/using-workflows/reusing-workflows
      uses: rmoreirao/AzureLearning/.github/workflows/02-github-ci-cd-workflow-generic.yml@main
      with:
        environment: prod
        location: ${{ inputs.location }}
        location_suffix: ${{ inputs.location_suffix }}